import Head from "next/head";
import React, { FC } from "react";
import { AuthWrapper } from "../../components/AuthWrapper";
import AccountLayout from "../../components/layouts/AccountLayout";

interface IProps {}

/**
 * @author @CodeYourEmpire
 * @function @Bookings
 **/

const Bookings: FC<IProps> = (props) => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          <div className="p-2 mt-4">
            <h3>Bookings</h3>
          </div>
        </AccountLayout>
      </AuthWrapper>
    </>
  );
};

export default Bookings;
