import Head from "next/head";
import React, { FC } from "react";
import { AuthWrapper } from "../../components/AuthWrapper";
import AccountLayout from "../../components/layouts/AccountLayout";

interface EarningsProps {}

/**
 * @author @CodeYourEmpire
 * @function @Earnings
 **/

const Earnings: FC<EarningsProps> = (props) => {
  return (
    <>
      <Head>
        <title>Trips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          <div className="p-2 mt-4">
            <h3>Your Earnings</h3>
          </div>
        </AccountLayout>
      </AuthWrapper>
    </>
  );
};

export default Earnings;
