import Head from "next/head";
import React, { FC } from "react";
import { AuthWrapper } from "../../components/AuthWrapper";
import { ComingSoon } from "../../components/ComingSoon";
import AccountLayout from "../../components/layouts/AccountLayout";

interface IProps {}

/**
 * @author
 * @function @Notifications
 **/

const Notifications: FC<IProps> = (props) => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          {/* <div className="p-2"></div> */}
          {/* <h3>Your notifications</h3> */}
          <ComingSoon title="All your notifications will appear here." />
        </AccountLayout>
      </AuthWrapper>
    </>
  );
};

export default Notifications;
