import Head from "next/head";
import React from "react";
import { AuthWrapper } from "../../components/AuthWrapper";
import { useRole } from "../../components/hooks/useRole";
import AccountLayout from "../../components/layouts/AccountLayout";
import { useAppSelector } from "../../redux/hooks";

interface SettingsProps {}

/**
 * @author @CodeYourEmpire
 * @function @Settings
 **/

const Settings = (props: SettingsProps) => {
  const token = useAppSelector((state) => state.auth._id);
  const role = useRole(token);
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          <div className="p-2">
            <h3>Your settings</h3>

            {role === 1 && (
              <div className="manageAccountWrapper">
                <button disabled={true}>Upgrade Account</button>
              </div>
            )}
            {role === 2 && (
              <div className="manageAccountWrapper">
                <button disabled={true}>Downgrade Account</button>
              </div>
            )}
          </div>
        </AccountLayout>
      </AuthWrapper>
    </>
  );
};

export default Settings;
