import Head from "next/head";
import React from "react";
import { ChatUserProfile } from "../../../components/Account/Chats/ChatUserProfile";
import { Messages } from "../../../components/Account/Chats/Messages";
import { AuthWrapper } from "../../../components/AuthWrapper";
import { useRole } from "../../../components/hooks/useRole";
import AccountLayout from "../../../components/layouts/AccountLayout";
import { useAppSelector } from "../../../redux/hooks";

interface ChatsProps {}

const Chats = (props: ChatsProps) => {
  const token = useAppSelector((state) => state.auth._id);
  const role = useRole(token);
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          <div className="chats-wrapper">
            <div>
              <div className="chat-top p-3">
                <input
                  type="text"
                  className="form-control"
                  placeholder="Search chat user..."
                />
              </div>
              <div className="chat-user-profiles">
                <div className="chat-sm-top" />
                <ChatUserProfile />
                <ChatUserProfile />
                <ChatUserProfile />
                <ChatUserProfile />
                <ChatUserProfile />
                <ChatUserProfile />
                <ChatUserProfile />
              </div>
            </div>
            <div className="chat-messages-lg-wrapper">
              <Messages />
            </div>
          </div>
        </AccountLayout>
      </AuthWrapper>
    </>
  );
};

export default Chats;
