import Head from "next/head";
import React from "react";
import { Messages } from "../../../components/Account/Chats/Messages";
import { AuthWrapper } from "../../../components/AuthWrapper";
import AccountLayout from "../../../components/layouts/AccountLayout";

interface ChatsProps {}

const ChatMediumMessages = (props: ChatsProps) => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          <Messages />
        </AccountLayout>
      </AuthWrapper>
    </>
  );
};

export default ChatMediumMessages;
