import Head from "next/head";
import React, { FC } from "react";

interface CustomHeadProps {
  title: string;
}

export const CustomHead: FC<CustomHeadProps> = (props) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
      />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Archivo:wght@900&family=Roboto:ital,wght@0,400;0,900;1,300&display=swap"
        rel="stylesheet"
      />
      <script src="https://maps.googleapis.com/maps/api/js?v=weekly&key=AIzaSyArIv424bNBpfMVIWSnie8aX1WGDI4wTDk&libraries=places"></script>
    </Head>
  );
};
