import Head from "next/head";
import React, { FC } from "react";

interface CustomHeadProps {
  title: string;
}

export const CustomHead: FC<CustomHeadProps> = (props) => {
  return (
    <Head>
      <title>{props.title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
