import Head from "next/head";
import { useRouter } from "next/router";
import React, { FC, useEffect, useState } from "react";
import { FormWrapper } from "../../../../../components/AddEditCar/FormWrapper";
import { AuthWrapper } from "../../../../../components/AuthWrapper";
import AccountLayout from "../../../../../components/layouts/AccountLayout";
import { Loading } from "../../../../../components/Loading";
import {
  Car,
  useGetCarQuery,
  useGetPrivateCarQuery,
} from "../../../../../graphql_types/generated/graphql";

interface EditCarProps {}

/**
 * @author @CodeYourEmpire
 * @function @EditCar
 **/

const EditCar: FC<EditCarProps> = (props) => {
  const router = useRouter();
  const [car, setCar] = useState<Car | null>();
  const [skip, setSkip] = useState(true);
  const [mainLoading, setMainLoading] = useState(true);

  const carId = parseInt(router.query.id as string, 10);

  useEffect(() => {
    if (carId) {
      setSkip(false);
    }
  }, [carId]);

  const { data, loading } = useGetPrivateCarQuery({
    variables: { carId },
    skip,
  });

  useEffect(() => {
    if (carId && data?.getCar) {
      setCar(data?.getCar.car);
    }
  }, [carId, data]);

  useEffect(() => {
    if (!loading && data?.getCar.car) {
      setMainLoading(false);
    }
  }, [loading, data]);

  console.log("data :>> ", data);

  // console.log("carId :>> ", carId);

  // console.log("car :>> ", car);

  return (
    <>
      {" "}
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountLayout>
        <AuthWrapper>
          {mainLoading ? (
            <Loading />
          ) : (
            <div className="p-2 mt-4">
              {" "}
              <h3 className="mb-3">Car Details</h3>
              <FormWrapper isEdit carId={carId} car={car} />
            </div>
          )}
        </AuthWrapper>
      </AccountLayout>
    </>
  );
};

export default EditCar;
