import Head from "next/head";
import React, { FC } from "react";
import { FormWrapper } from "../../../components/AddEditCar/FormWrapper";
import { AuthWrapper } from "../../../components/AuthWrapper";
import AccountLayout from "../../../components/layouts/AccountLayout";

interface AddCarProps {}

/**
 * @author @CodeYourEmpire
 * @function @AddCar
 **/

const AddCar: FC<AddCarProps> = (props) => {
  // const [currentOpenExpandable, setCurrentOpenExpandable] = useState<number>(0);
  // console.log("currentOpenExpandable :>> ", currentOpenExpandable);

  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AccountLayout>
        <AuthWrapper>
          <div className="p-2 mt-4">
            <h3 className="mb-3">Car Details</h3>
            <FormWrapper />
          </div>
        </AuthWrapper>
      </AccountLayout>
    </>
  );
};

export default AddCar;
