import Head from "next/head";
import React, { FC, useState } from "react";
import Layout from "../../components/layouts/Layout";
import Link from "next/link";
import { AuthWrapper } from "../../components/AuthWrapper";

interface ApproveDriverProps {}

/**
 * @author @CodeYourEmpire
 * @function @ApproveDriver
 **/

const ApproveDriver: FC<ApproveDriverProps> = (props) => {
  const [values, setValues] = useState({});

  const handleChange = () => {};
  return (
    <>
      <Head>
        <title>FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <Layout>
          <div className="customContainer my-4">
            <h1>Get Approved To Drive</h1>
            <p>
              Since this is your first time we would like you to provide us with
              some information
            </p>
            <form className="form-group">
              <div className="mb-3">
                <div className="mb-3">
                  <label htmlFor="email">Email Address</label>
                  {/* Email will never be changed  */}
                  <input
                    className="form-control"
                    required
                    id="email"
                    //   value={values.email}
                    placeholder="johndoe@gmail.com"
                    onChange={handleChange}
                    name="email"
                  />
                </div>
                <label htmlFor="email">Phone Number</label>
                <input
                  className="form-control"
                  required
                  id="email"
                  // value={values.email}
                  placeholder="johndoe@gmail.com"
                  onChange={handleChange}
                  name="email"
                />
              </div>
              <div className="mb-3">
                <label htmlFor="email">Driving License No.</label>
                <input
                  className="form-control"
                  required
                  id="email"
                  // value={values.email}
                  placeholder="johndoe@gmail.com"
                  onChange={handleChange}
                  name="email"
                />
              </div>
              <div className="d-grid gap-2 mt-3">
                <Link
                  href={{
                    pathname: "/checkout/confirm-order",
                    query: {},
                  }}
                >
                  <button type="submit" className="btn bgOrange">
                    Continue
                  </button>
                </Link>
              </div>
            </form>
          </div>
        </Layout>
      </AuthWrapper>
    </>
  );
};

export default ApproveDriver;
