import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import { AuthWrapper } from "../../components/AuthWrapper";
import Layout from "../../components/layouts/Layout";

const CheckoutSuccess: NextPage = () => {
  const [mainLoading, setMainLoading] = useState(true);
  const router = useRouter();
  const [skip, setSkip] = useState(true);

  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <Layout>
          {/* {mainLoading ? (
            <Loading />
          ) : ( */}
          <div className="customContainer my-4">
            <div className="row">
              <div className="col-md-8 mx-auto">
                <h3>We've got it</h3>

                <p>
                  Your reservation has been received. The host has received it
                  and will reach back to you with confirmation and more details.
                  You can track your reservation status{" "}
                  <Link href="/">
                    <a className="colorOrange">here</a>
                  </Link>
                  .
                </p>

                <h5 className="mt-4">Reservation Details</h5>
                <div className="container p-0">
                  <div className="row m-0">
                    <div className="col-5 col-md-6 p-0">
                      <img
                        src="/images/subaru.jpg"
                        className="success-car-image"
                      />
                    </div>
                    <div className="col-7 col-md-6">
                      <h5>Subaru Impreza</h5>
                      <p>Transmission:Manual</p>
                      <p>Seats:5</p>
                      <p>Doors:5</p>
                      <p>Daily Rate:Ksh.5000</p>
                    </div>
                  </div>
                </div>
                <hr />
                <div className="container p-0">
                  <div className="row m-0">
                    <div className="col-6 p-0">
                      <p>Sub Total:</p>
                    </div>
                    <div className="col-6 d-flex justify-content-end">
                      <p>6*5000 = Ksh.30000</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* )} */}
        </Layout>
      </AuthWrapper>
    </>
  );
};

export default CheckoutSuccess;
