import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layouts/Layout";
import { faqs } from "../data/faqs";
import parse from "html-react-parser";
import Link from "next/link";

const FAQS: NextPage = () => {
  return (
    <>
      <Head>
        <title>FAQs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="customContainer my-4">
          <h3 className="my-5 text-center">FREQUENTLY ASKED QUESTIONS</h3>
          <div className="accordion" id="accordionPanelsStayOpenExample">
            {faqs.map((faq, idx) => (
              <div className="accordion-item">
                <h2
                  className="accordion-header"
                  id={`panelsStayOpen-heading${idx}`}
                >
                  <button
                    className={`accordion-button faq-accordion-button ${
                      idx !== 0 && `collapsed`
                    }`}
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target={`#panelsStayOpen-collapse${idx}`}
                    aria-expanded={idx === 0 ? true : false}
                    aria-controls={`panelsStayOpen-collapse${idx}`}
                  >
                    {faq.title}
                  </button>
                </h2>
                <div
                  id={`panelsStayOpen-collapse${idx}`}
                  className={`accordion-collapse collapse ${
                    idx === 0 && `show`
                  }`}
                  aria-labelledby={`panelsStayOpen-heading${idx}`}
                >
                  <div className="accordion-body">{parse(faq.content)}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
};

export default FAQS;
