import type { NextPage } from "next";
import Head from "next/head";
import { BrowseByMake } from "../components/Home/BrowseByMake";
import Hero from "../components/Home/Hero";
import { HeroBottom } from "../components/Home/HeroBottom";
// import HowItWorks from "../components/Home/HowItWorks";
import { PopularCars } from "../components/Home/PopularCars";
import Layout from "../components/layouts/Layout";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Caradil Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="/css/slick.css" />
        <link rel="stylesheet" type="text/css" href="/css/slick-theme.css" />
      </Head>
      <Layout isHome>
        <Hero />
        <HeroBottom />
        {/* <HowItWorks /> */}
        <PopularCars />
        <BrowseByMake />
      </Layout>
    </>
  );
};

export default Home;
