import Head from "next/head";
import router from "next/router";
import React, { ReactElement } from "react";
import { BsArrowLeft } from "react-icons/bs";
import { AuthWrapper } from "../../../components/AuthWrapper";
import AccountLayout from "../../../components/layouts/AccountLayout";

interface Props {}

export default function Booking(props: Props): ReactElement {
  return (
    <>
      <Head>
        <title>Booking</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthWrapper>
        <AccountLayout>
          <div className="p-2 mt-4">
            {/* <h3>Helloo</h3> */}
            <button
              className="btn m-0 p-0"
              onClick={() => {
                router.replace("/account/bookings");
              }}
            >
              <BsArrowLeft size={"30px"} />
            </button>
          </div>
        </AccountLayout>
      </AuthWrapper>
    </>
  );
}
