import Head from "next/head";
import React, { FC } from "react";
import AdminLayout from "../../components/layouts/AdminLayout";

interface IProps {}

/**
 * @author
 * @function @Account
 **/

const Admin: FC<IProps> = (props) => {
  return (
    <>
      <Head>
        <title>Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout></AdminLayout>
    </>
  );
};

export default Admin;
